DROP TABLE IF EXISTS PRODUCT_DETAILS;
DROP TABLE IF EXISTS PRODUCT_SIZE_DETAILS;
 
CREATE TABLE PRODUCT_DETAILS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  PROD_ID VARCHAR(250) NOT NULL,
  PROD_NAME VARCHAR(250) NOT NULL,
  PROD_PRICE INT NOT NULL,
  PROD_SELL_PRICE INT 
);

CREATE TABLE PRODUCT_SIZE_DETAILS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  PROD_ID VARCHAR(250) NOT NULL,
  PROD_AVAIL_ID CHAR(1) NOT NULL,
  PROD_SIZE VARCHAR(250) NOT NULL
);


